with raw_drz_data as (
    select 
    DELIVERED_DATE,
    ORDER_ID,
    BRAND_NAME,
    CATALOG_ITEM_NAME,
    RAW_ITEM_NAME,
    TOP_LEVEL_CATEGORY,
    TOP_SUBCATEGORY,
    SUBCATEGORY,
    CATALOG_ITEM_ID,
    DELIVERY_STATE,
    DELIVERY_ZIPCODE,
    STORE_MARKET,
    CONTAINER_QTY,
    CONTAINER_TYPE,
    VOLUME,
    VOLUME_UNITS,
    UNIT_PRICE,
    VERIFIED_UPC,
    FULFILLMENT_TYPE,
    NEW_VS_RETURNING,
    DEVICE,
    TOTAL_QUANTITY,
    TOTAL_GMV
    from {{ source('drizzly_raw_sources', 'drizzly_sales_daily') }}
  ), 
  datatype_adjusted_data as (
  select to_date(DELIVERED_DATE,'YYYY-MM-DD') as DELIVERED_DATE ,
    cast(ORDER_ID as integer) as ORDER_ID,
    BRAND_NAME,
    CATALOG_ITEM_NAME,
    RAW_ITEM_NAME,
    TOP_LEVEL_CATEGORY,
    TOP_SUBCATEGORY,
    SUBCATEGORY,
    CATALOG_ITEM_ID,
    DELIVERY_STATE,
    try_cast(DELIVERY_ZIPCODE as integer) as DELIVERY_ZIPCODE,
    STORE_MARKET,
    try_cast(CONTAINER_QTY as BIGINT) as CONTAINER_QTY,
    CONTAINER_TYPE,
    try_cast(VOLUME as BIGINT) as LIQUOR_VOLUME,
    VOLUME_UNITS,
    try_cast(UNIT_PRICE as DOUBLE) as UNIT_PRICE,
    VERIFIED_UPC,
    FULFILLMENT_TYPE,
    NEW_VS_RETURNING,
    DEVICE,
    try_cast(TOTAL_QUANTITY as BIGINT) as TOTAL_QUANTITY,
    try_cast(TOTAL_GMV as DECIMAL) as TOTAL_GMV
from raw_drz_data
)
select * from datatype_adjusted_data