select 
_AIRBYTE_RAW_ID,
_AIRBYTE_EXTRACTED_AT,
_AIRBYTE_META,
AAB,
BRAND,
COLOR,
try_cast(REPLACE(REPLACE("$ SALES",'$',''),',','') as integer) as SALES,
"$ SHARE" as SHARE,
"CBI FLG" as CBI_FLG,
CATEGORY,
GEOGRAPHY,
try_cast(REPLACE("VOLUME YA",',','') as double) as VOLUME_YA,
try_cast(REPLACE(REPLACE("$ SALES YA",'$',''),',','') as integer) as SALES_YA,
"$ SHARE YA" as SHARE_YA,
try_cast(REPLACE("UNIT SALES",',','') as integer) as UNIT_SALES,
"BEV SEGMENT" as bev_segment,
DESCRIPTION,
"BRAND FAMILY" as brand_family,
"FLAVOR SCENT" as FLAVOR_SCENT,
try_cast(REPLACE("VOLUME SALES",',','') as integer) as VOLUME_SALES,
try_cast(REPLACE("UNIT SALES YA",',','') as integer) as UNIT_SALES_YA,
try_cast(REPLACE("AVG 750ML PRICE",'$','') as double) as avg_750ml_price,
"DOM VS IMP VALUE" as dom_vs_imp_value,
try_cast(REPLACE("AVG 750ML PRICE YA",'$','') as double) as avg_750ml_price_ya,
"CUSTOM BRAND GROUP" as CUSTOM_BRAND_GROUP,
_AB_SOURCE_FILE_URL,
"TTL PTS CUM WEEKS CWD" as ttl_pts_cum_weeks_cwd,
"GEOGRAPHY CLASSIFICATION" as geo_classification, 
"TTL PTS CUM WEEKS CWD YA" as ttl_pts_cum_weeks_cwd_ya,
_AB_SOURCE_FILE_LAST_MODIFIED
    from 
{{ source('iri_raw_sources', 'IRI_SALES_DAILY_WINE') }}