select 
_AIRBYTE_RAW_ID,
_AIRBYTE_EXTRACTED_AT,
_AIRBYTE_META,
AAB,
SIZE as CONTAINER_SIZE,
TIME as WEEK_NAME,
BRAND,
STATE,
STYLE,
FLAVOR,
try_cast(REPLACE(REPLACE("$ SALES",'$',''),',','') as integer) as SALES,
"$ SHARE" as SHARE,
"CBI FLG" as CBI_FLG,
PACKAGE,
SEGMENT,
CATEGORY,
SUPPLIER,
GEOGRAPHY,
try_cast(REPLACE(REPLACE("$ SALES YA",'$',''),',','') as integer) as SALES_YA,
"$ SHARE YA" as SHARE_YA,
"TYPE VALUE" as TYPE_VALUE,
try_cast(REPLACE("UNIT SALES",',','') as integer) as UNIT_SALES,
"BEV SEGMENT" as BEV_SEGMENT,
SUBCATEGORY,
"BRAND FAMILY" as brand_family,
"UPC 13 DIGIT" as upc_13_digit,
try_cast("VOLUME SALES" as integer) as volume_sales,
"PRICE SEGMENT" as price_segement,
"RMA_CROM FLAG" as RMA_CROM_FLG,
try_cast("UNIT SALES YA" as integer) as UNIT_SALES_YA,
"MAJOR CATEGORY" as MAJOR_CATEGORY,
try_cast(REPLACE("AVG 750ML PRICE",'$','') as double) as avg_750ml_price,
"IRI ASPIRA TIER" as iri_aspira_tier,
try_cast("VOLUME SALES YA" as integer) as volume_sales_ya,
"DOM VS IMP VALUE" as dom_vs_imp_value,
"ITEM DESCRIPTION" as item_description,
"POWER BRAND FLAG" as power_brand_flg,
try_cast(REPLACE("AVG 750ML PRICE YA",'$','') as double) as avg_750ml_price_ya,
"PRICE SEGMENT GROUP" as price_segement_grp,
"PRODUCT DESCRIPTION" as product_desc,
_AB_SOURCE_FILE_URL,
"IRI PORTFOLIO SEGMENT" as iri_portfolio_segment,
try_cast("TTL PTS CUM WEEKS CWD" as integer) as ttl_pts_cum_weeks_cwd,
"GEOGRAPHY CLASSIFICATION" as geo_classification,
"IRI BRAND PRIORITY GROUP" as iri_brang_priority_grp,
try_cast("TTL PTS CUM WEEKS CWD YA" as integer) as ttl_pts_cum_weeks_cwd_ya, 
"IRI FY NATIONAL FOCUS BRAND" as iri_fy_national_focus,
_AB_SOURCE_FILE_LAST_MODIFIED
    from 
{{ source('iri_raw_sources', 'IRI_SALES_DAILY_SPIRITS') }}